on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Mod download
      run: go mod download
    - name: Vet
      run: go vet ./...
    - name: Test
      run: go test ./...
    - name: Enforce Go Formatted Code
      run: "! go fmt ./... 2>&1 | read"
